#!/bin/bash
# Regenerate and validate the ops/agents/ launcher shims.
#
# Why these exist: macOS System Settings → Login Items & Extensions → Background
# App Activity names each LaunchAgent after the *basename of ProgramArguments[0]*.
# Pointing a plist straight at .venv/bin/python produces a row called "python" —
# and we have nine of them, indistinguishable from each other and from Selene's.
# So every agent gets its own launcher file named exactly what should appear in
# that list, and the plist points at the launcher.
#
# A bare symlink to .venv/bin/python would NOT work here: CPython locates
# pyvenv.cfg relative to the invoked executable's directory, so a symlink outside
# .venv/bin/ silently drops the venv's site-packages and the job runs against
# system Python. Hence a real shim that execs the venv interpreter by full path.
#
# Run after a venv rebuild or when adding an agent. Safe to re-run.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="$REPO/.venv/bin/python"
AGENTS_DIR="$REPO/ops/agents"

# "<display name>|<program>|<args...>"  — display name is the Settings row label.
LAUNCHERS=(
  "KitchenOS · API|$PY|$REPO/api_server.py"
  "KitchenOS · Batch Extract|$PY|$REPO/batch_extract.py"
  "KitchenOS · Calendar Sync|$PY|$REPO/sync_calendar.py"
  "KitchenOS · Cleanup iCloud|/bin/bash|$REPO/scripts/cleanup_old_icloud.sh"
  "KitchenOS · Dashboard Update|$PY|$REPO/scripts/update_dashboard_canvas.py"
  "KitchenOS · Enrich Recipes|$PY|$REPO/scripts/enrich_recipes.py|--out|$REPO/logs/enrich-latest.json"
  "KitchenOS · Meal Plan|$PY|$REPO/generate_meal_plan.py"
  "KitchenOS · Receipt Ingest|$PY|$REPO/ingest_receipts.py"
  "KitchenOS · Verdict Nudge|$PY|$REPO/scripts/nudge_verdicts.py"
)

mkdir -p "$AGENTS_DIR"
fail=0

for entry in "${LAUNCHERS[@]}"; do
    IFS='|' read -r -a parts <<< "$entry"
    name="${parts[0]}"
    program="${parts[1]}"
    args=("${parts[@]:2}")

    if [ ! -x "$program" ]; then
        echo "ERROR: interpreter missing or not executable: $program" >&2
        echo "       (venv rebuilt? run: python3.11 -m venv .venv && .venv/bin/pip install -r requirements.txt)" >&2
        fail=1
        continue
    fi
    if [ ! -f "${args[0]}" ]; then
        echo "ERROR: target script missing for '$name': ${args[0]}" >&2
        fail=1
        continue
    fi

    # Build the exec line with each argument quoted independently.
    exec_line="exec \"$program\""
    for a in "${args[@]}"; do
        exec_line="$exec_line \\
     \"$a\""
    done

    cat > "$AGENTS_DIR/$name" <<EOF
#!/bin/bash
# Launcher shim — GENERATED by scripts/make-agent-launchers.sh, do not edit.
# The filename is what macOS shows in System Settings → Login Items &
# Extensions → Background App Activity. See ~/Dev/CLAUDE.md.
$exec_line "\$@"
EOF
    chmod +x "$AGENTS_DIR/$name"
    echo "ok: $name"
done

# Every plist must point at a launcher that exists, and never at a bare interpreter.
for plist in "$REPO"/ops/com.kitchenos.*.plist; do
    prog=$(/usr/libexec/PlistBuddy -c "Print :ProgramArguments:0" "$plist" 2>/dev/null || true)
    label=$(basename "$plist" .plist)
    case "$(basename "$prog")" in
        python|python3|python3.*|node|bash|zsh|sh)
            echo "ERROR: $label points at a bare interpreter ($prog)" >&2
            fail=1 ;;
    esac
    if [ -n "$prog" ] && [ ! -x "$prog" ]; then
        echo "ERROR: $label points at a missing launcher: $prog" >&2
        fail=1
    fi
done

if [ "$fail" -ne 0 ]; then
    echo "FAILED" >&2
    exit 1
fi
echo "All ${#LAUNCHERS[@]} launchers present and all plists validated."
